server_web_homepage:
    pattern:  /home/
    defaults: { _controller: ServerWebBundle:Default:index }

server_web_channel:
    pattern:  /channel/{code}
    defaults: { _controller: ServerWebBundle:Default:channel }