parameters:
#    server_web.example.class: Server\WebBundle\Example

services:
#    server_web.example:
#        class: %server_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
